"""Add role to User model

Revision ID: 121dd3df14b1
Revises: 5325f7f0b459
Create Date: 2024-10-07 12:53:54.493496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121dd3df14b1'
down_revision = '5325f7f0b459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
