"""added more fields to booking

Revision ID: 16479ffcbe5e
Revises: b3d8d2ea45d2
Create Date: 2024-09-16 23:54:34.809385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16479ffcbe5e'
down_revision = 'b3d8d2ea45d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('service_difficulty', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('service_difficulty')
        batch_op.drop_column('service_name')

    # ### end Alembic commands ###
