"""added price

Revision ID: 243eb37498c8
Revises: 841c8bea4e5d
Create Date: 2024-08-12 14:21:49.329563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243eb37498c8'
down_revision = '841c8bea4e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
