"""removed service_id

Revision ID: 36e490ab81da
Revises: aa082f6b7b8c
Create Date: 2024-09-17 02:07:41.985300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e490ab81da'
down_revision = 'aa082f6b7b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('booking_service_id_fkey', 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###
