"""add service_id

Revision ID: 660f72e12c7d
Revises: 121dd3df14b1
Create Date: 2024-10-07 13:40:05.000318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660f72e12c7d'
down_revision = '121dd3df14b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
