"""Added category to Service model

Revision ID: 841c8bea4e5d
Revises: 868edf6b3016
Create Date: 2024-08-12 13:47:53.566097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841c8bea4e5d'
down_revision = '868edf6b3016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=1000), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
