"""empty message

Revision ID: 868edf6b3016
Revises: f39cc7d84cba
Create Date: 2024-08-11 00:49:55.166646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868edf6b3016'
down_revision = 'f39cc7d84cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
