"""added location to booking

Revision ID: b3d8d2ea45d2
Revises: 304c08a1410a
Create Date: 2024-09-16 23:40:38.220840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d8d2ea45d2'
down_revision = '304c08a1410a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('street')
        batch_op.drop_column('town')
        batch_op.drop_column('county')

    # ### end Alembic commands ###
